apply plugin: 'java'
apply plugin: 'application'

mainClassName = 'org.ClientMain'

repositories {
    mavenCentral()
}

dependencies {
    // Добавь зависимости при необходимости
}

jar {
    manifest {
        attributes(
                'Main-Class': mainClassName
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}